### ISSUE TITLE
online javascript --> offline javascript

### ISSUE THREAD

**Issue by AIDevCom** [AIDeveloperCommunity/aidevelopercommunity.github.io#11]

**Comment by crespoter** [comment]
Wouldnt it better if we have the js and css files loaded over from the cdn provider to reduce the load on our server.

**Comment by SriHarshaGajavalli** [comment]
Well, this is also a good point. But we should definitely look into
something which can load the website faster

‌


*Sri Harsha Gajavalli*
*B.Tech - 3rd Year*
*Computer Science and Engineering*
*IIIT Chittoor*
*Sri City-517588*
*(+91)-91007 53548*

**Comment by crespoter** [comment]
The new template doesnt seem to have the loading issues.
Close this issue?
