### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by CallMeFib3r** [AIDeveloperCommunity/aidevelopercommunity.github.io#12]
Hi,

@crespoter informed me that the AI Developer Community was in the need of a logo. Therefore I went ahead and created a fitting logo. Before we proceed I want to say that this logo is completely free of charge so you should consider it as a contribution. I will be getting rewarded on the utopian.io platform so don't worry about the monetary aspect.

Let's take a look at the logo.

The aim of the community is to share the knowledge of artificial intelligence through meetups and training sessions. I figured this should be the starting point for the entire logo. I attempted to (literally) connect the knowledge element with the AI facto. I visualized the knowledge element through a book and the AI element by a face. I then connected both elements accordingly.

I hope you guys will like this proposal. If you have any more questions feel free to ask. 
If you guys are pleased with the logo I will go ahead and send all the files.

![ai_dev_comm-06](https://user-images.githubusercontent.com/37731582/39096296-31043aee-464e-11e8-8e52-1fccad940011.png)
![ai_dev_comm-05](https://user-images.githubusercontent.com/37731582/39096295-30eb939a-464e-11e8-96b3-24ab97c91bdf.png)
![ai_dev_comm_monochrome-04](https://user-images.githubusercontent.com/37731582/39096294-30d19d82-464e-11e8-9220-87d90f86e6ef.png)

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons-Licentie" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International-License</a>.

**Comment by crespoter** [comment]
@AIDevCom , Have a look at this one.

**Comment by SriHarshaGajavalli** [comment]
Hey,
@CallMeFib3r, we are so happy to see your efforts in coming with such a great logo and we are pretty sure your contributions matter a lot to the development of this open-source organization.

Small feedback from my side it is a bit heavy(kind of). is it possible to make it simpler by removing a few elements such as bottom parts of the book and their dependencies? Also, the style of the name can be modified.

Once again thank you so much for becoming the part of the great cause by giving your contribution.

**Comment by CallMeFib3r** [comment]
Thanks for the feedback! I'm happy to hear that my work is appreciated.
I went ahead and removed excessive parts yet maintaining the fundamental elements of the logo. I hope you guys like it better this way. The font has also been changed.
![ai_dev_comm-08](https://user-images.githubusercontent.com/37731582/39141922-759a839e-4729-11e8-9844-7b53e61770f4.png)

**Comment by SriHarshaGajavalli** [comment]
Hey, 

I really appreciate your efforts. Thank you once again for your contributions to the organization. Some discussions are going on and we will get back to you with updates in a couple of days.

**Comment by SriHarshaGajavalli** [comment]
Hi @CallMeFib3r 

After all discussions, we have decided to chose the latter one. Thank you so much for your contribution. They mean a lot to us. I would like to have all the further communication in the mail. Hence I am closing this issue now.

**Comment by CallMeFib3r** [comment]
As requested via email I provided all the files in the suitable size. 
Files are available here https://drive.google.com/drive/folders/1_BHbzzKwEVCWRi73X7ySDlDNvhVr6vM3?usp=sharing.
