### ISSUE TITLE
Codacy Integration

### ISSUE THREAD

**Issue by SriHarshaGajavalli** [AIDeveloperCommunity/aidevelopercommunity.github.io#22]
Integrate with Codacy for code quality assurance

**Comment by crespoter** [comment]
I presume this is done?

**Comment by SriHarshaGajavalli** [comment]
This is done. Just looking to integrate codacy not with slack channel

**Comment by crespoter** [comment]
Codacy has been integrated.

**Comment by crespoter** [comment]
Closing this issue
