### ISSUE TITLE
Fix social links

### ISSUE THREAD

**Issue by SriHarshaGajavalli** [AIDeveloperCommunity/aidevelopercommunity.github.io#37]
A few social links are broken. Need to fix them up.

**Comment by soham1705** [comment]
@SriHarshaGajavalli or @crespoter could you rectify the name of the Github organisation on the Facebook page?

**Comment by crespoter** [comment]
I have replaced the google plus link with the meetup one. Any ideas on what to replace the twitter one with?

**Comment by SriHarshaGajavalli** [comment]
Perfect. Why not having Google plus linked to g+ profile of our email id.

**Comment by crespoter** [comment]
Okay
This is done.
